version: '3.4'

networks:
  medicalscan_network:

services:
  medicalscandb:
    container_name: medical-scan-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 8002:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=passWord@12345#
    networks:
        - medicalscan_network
  medicalscan:
    container_name: medical-scan
    image: medicalscan:latest
    build:
      context: .
      dockerfile: MedicalScan/Dockerfile
    ports:
        - 8001:80
    depends_on:
        - medicalscandb
    environment:
        - ConnectionStrings__DataConnection=Server=medicalscandb;Initial Catalog=MedicalScan;User Id=sa;Password=passWord@12345#;TrustServerCertificate=True;MultiSubnetFailover=True
    networks:
        - medicalscan_network